/**
 * Heirloom user-facing strings. Every line states a fact the user needs.
 * Sourced from docs/DESIGN.md and specs/client-ui.md.
 */

import { Status } from './api/types';

export const COPY = {
  brand: {
    name: 'Heirloom',
    sampleNotice: 'Figures on this page are sample data.',
  },
  header: {
    defaultCollection: 'Collection HL-0007',
    defaultRole: 'Owner',
    divider: ' · ',
    create: 'Create collection',
    addItem: 'Catalogue an item',
    itemDetail: 'Item detail',
    guardians: 'Guardians and readiness',
    changes: 'Queued policy changes',
    rotate: 'Rotate secrets',
  },
  nav: {
    register: 'Collection',
    create: 'Create',
    guardians: 'Guardians',
    changes: 'Changes',
    devStates: 'States',
    devTokens: 'Tokens',
  },
  restrictionLine: {
    [Status.Sealed]: {
      value: 'Closed',
      note: 'Last owner signature 02 Oct. Nothing pending.',
    },
    [Status.Armed]: {
      value: 'Closed',
      note: '2 of 3 attestations filed. The owner has been told.',
    },
    [Status.Silent]: {
      value: 'Closed',
      note: 'Owner silent since 19 Aug. No attestations yet.',
    },
    [Status.Cooling]: {
      label: 'Opens in',
      value: '1 d 04 h',
      note: 'The owner may cancel until then.',
    },
    [Status.Disputed]: {
      value: 'Frozen',
      note: 'One guardian reported the owner alive.',
    },
    [Status.Releasable]: {
      value: 'Open',
      note: 'Guardians may now hand over their shares.',
    },
    [Status.ContingentEligible]: {
      label: 'Primary claim period lapsed',
      value: 'Open',
      note: 'The contingent beneficiary may claim.',
    },
    [Status.Claimed]: {
      value: 'Claimed 12 Nov',
      note: 'Rotate the secrets in this item.',
    },
  },
  states: {
    empty: 'No items are catalogued in this collection yet. Add the first one to set its restriction.',
    loadingPrefix: 'Reading the chain, block ',
    defaultLoadingBlock: '14,203,118',
    error: 'The chain did not answer. Nothing was changed. Retry, or submit directly from a wallet.',
    errorFixPrompt: 'Check the network connection, or submit directly from a wallet.',
  },
  stamps: {
    [Status.Sealed]: 'SEALED',
    [Status.Armed]: 'ARMED',
    [Status.Silent]: 'SILENT',
    [Status.Cooling]: 'COOLING',
    [Status.Disputed]: 'DISPUTED',
    [Status.Releasable]: 'RELEASABLE',
    [Status.ContingentEligible]: 'CONTINGENT',
    [Status.Claimed]: 'CLAIMED',
  },
  table: {
    accession: 'Accession',
    item: 'Item',
    contents: 'Contents',
    quorum: 'Quorum',
    window: 'Window',
    status: 'Status',
  },
  summary: {
    owner: 'Owner',
    custodians: 'Custodians',
    items: 'Items',
    lastSigned: 'Last signed',
    epoch: 'Epoch',
    chain: 'Chain',
  },
  actions: {
    catalogueItem: 'Catalogue an item',
    submitShare: 'Submit share',
    claimAsset: 'Claim item',
    cancelProtocol: 'Cancel release',
    retry: 'Retry',
    submit: 'Submit',
    back: 'Back',
  },
  fields: {
    accessionLabel: 'Accession number',
    titleLabel: 'Item title',
    beneficiaryLabel: 'Beneficiary',
    quorumLabel: 'Attestations required',
    inactivityLabel: 'Silence window',
  },
  createCollection: {
    pageTitle: 'Create collection',
    marginLabel: 'Vault',
    paragraph: 'A collection configures custodians, beneficiaries, and thresholds. Identity cards provide signing keys and encryption public keys.',
    guardiansLabel: 'Guardian identity cards',
    guardiansHint: 'Paste one base64url JSON identity card per line.',
    beneficiariesLabel: 'Beneficiary identity cards',
    beneficiariesHint: 'Paste one base64url JSON identity card per line.',
    tLabel: 'Threshold (t)',
    nLabel: 'Guardians (n)',
    policyDelayLabel: 'Policy delay (seconds)',
    warningSlack: 'n is less than t + 2: with fewer than t + 2 guardians, a single inactive guardian reduces fault tolerance.',
    errorBeneficiaryIsGuardian: 'A beneficiary cannot also be a guardian of the same item to prevent conflicts of interest.',
    errorNeedTwo: 'At least 2 guardians and 1 beneficiary are required.',
    errorThreshold: 'Threshold t must satisfy 2 ≤ t ≤ n.',
    sampleBtn: 'Insert sample cards',
    submitBtn: 'Create collection',
    cardKindInvalid: 'Invalid kind: must be 0 (EOA) or 1 (P-256).',
    cardAInvalid: 'Invalid key a: expected 32-byte hex.',
    cardBInvalid: 'Invalid key b: expected 32-byte hex.',
    cardEncPkInvalid: 'Invalid encPk: expected 32-byte public key.',
    cardJsonInvalid: 'Invalid base64url or JSON format.',
  },
  addItem: {
    pageTitle: 'Catalogue an item',
    marginLabel: 'Item policy',
    paragraph: 'An item specifies access conditions, custodian quorums, and beneficiaries. Choose a starting policy or configure rules manually.',
    startingPointsTitle: 'Starting policies',
    sp1Title: '1 Medical records',
    sp1Desc: '14-day inactivity, 7-day window, 2 guardians, signed certificate evidence required.',
    sp2Title: '2 Letters and account list',
    sp2Desc: '30-day inactivity, 14-day window, 3 guardians, evidence not required.',
    sp3Title: '3 Seed phrase and bank credentials',
    sp3Desc: '60-day inactivity, 30-day window, 3 guardians, evidence required.',
    accessionLabel: 'Accession number',
    titleLabel: 'Item title',
    contentsLabel: 'Contents description',
    reasonsLabel: 'Release reasons',
    reasonIncapacitated: 'Incapacitated',
    reasonDeceased: 'Deceased',
    reasonMissing: 'Missing',
    inactivityLabel: 'Silence window (days)',
    kAttestLabel: 'Attestation quorum (k)',
    evidenceLabel: 'Require digital-signature evidence',
    windowLabel: 'Release window (days)',
    deadlineLabel: 'Claim deadline (days)',
    primaryBenefLabel: 'Primary beneficiary key hash',
    contingentBenefLabel: 'Contingent beneficiary key hash',
    errorKAttest: 'Attestation threshold kAttest cannot exceed n − 1 so that dispute override remains reachable.',
    errorWindow: 'Release window must be greater than zero to allow the owner to intervene.',
    submitBtn: 'Catalogue item',
  },
  itemDetail: {
    conditionsHeading: 'Release conditions',
    silenceLabel: 'Owner silence',
    silenceActive: 'Active',
    silenceSilent: 'Silent',
    quorumLabel: 'Guardian quorum',
    quorumPending: 'Pending',
    quorumReached: 'Reached',
    windowLabel: 'Release window',
    windowClosed: 'Closed',
    windowRunning: 'Running',
    windowElapsed: 'Elapsed',
    attestationsHeading: 'Guardian attestations',
    guardianCol: 'Guardian',
    attestationMarkCol: 'Mark',
    attestationDateCol: 'Filed at',
    notFiled: 'Not filed',
    filed: 'Filed',
    attestationDispute: 'Dispute (ALIVE)',
    attestationIncapacitated: 'Attested (Incapacitated)',
    attestationDeceased: 'Attested (Deceased)',
    conditionPending: 'Awaiting quorum',
    tableHeaderCondition: 'Condition',
    tableHeaderRequirement: 'Requirement',
    tableHeaderStatus: 'Status',
    tableHeaderTimestamp: 'Timestamp',
    tableHeaderKeyId: 'Key ID',
    guardianLabelPrefix: 'Guardian',
    actionsHeading: 'Interventions',
    cancelBtn: 'Cancel release',
    cancelNote: 'A signature heartbeat that resets unreleased assets and increments epoch.',
    absenceBtn: 'Set planned absence',
    absenceDaysLabel: 'Absence duration (days)',
    absenceSetSuccess: 'Absence recorded on chain.',
    summaryHeading: 'Accession record',
    summaryAssetId: 'Asset ID',
    summaryPrimaryBenef: 'Primary beneficiary',
    summaryContingentBenef: 'Contingent beneficiary',
    summaryBundleCid: 'Bundle CID',
    summaryQuorum: 'Quorum',
    summaryWindow: 'Window',
    rotatePrompt: 'This item was previously released. Cancelling does not erase released shares.',
    rotateLink: 'Rotate secrets checklist',
    notFound: 'Item not found in this collection register.',
    returnLink: 'Return to collection',
  },
  guardians: {
    pageTitle: 'Guardians and readiness',
    marginLabel: 'Custodians',
    paragraph: 'Custodians hold Shamir shares and execute periodic readiness drills without viewing asset contents or each other.',
    summaryTotal: 'Custodians (n)',
    summaryThreshold: 'Threshold (t)',
    summaryReady: 'Drill-ready',
    summarySlack: 'Slack (ready − t)',
    slackWarning: 'Slack is less than 1. Any single guardian unavailability prevents threshold reconstruction.',
    colGuardian: 'Guardian',
    colDrillVer: 'Drill version',
    colDrillDate: 'Last drill date',
    colStatus: 'Readiness',
    ready: 'Ready',
    notReady: 'Not ready',
    empty: 'No guardians are registered for this collection.',
  },
  changes: {
    pageTitle: 'Queued policy changes',
    marginLabel: 'Timelock',
    paragraph: 'Changes that make a policy looser wait in queue for the policy delay period while custodians are alerted. The owner may revoke them at any time.',
    colChange: 'Queued change',
    colApplyAfter: 'Available to apply',
    colTimeLeft: 'Time remaining',
    colAction: 'Action',
    revokeBtn: 'Revoke change',
    empty: 'No policy changes are queued in the asymmetric timelock.',
  },
  rotate: {
    pageTitle: 'Rotate secrets',
    marginLabel: 'Rotation',
    paragraph: 'This item was released before cancellation. Cryptographic shares cannot be retracted once handed over. Complete the following rotation checklist to secure replacement assets.',
    step1Title: 'Revoke exposed credentials',
    step1Desc: 'Change passwords, API keys, and device passkeys previously held in this item.',
    step2Title: 'Generate replacement credentials',
    step2Desc: 'Create new cryptographic seed phrases or locker combinations.',
    step3Title: 'Re-seal item package',
    step3Desc: 'Re-encrypt the updated contents and compute fresh Shamir shares.',
    step4Title: 'Commit updated version on chain',
    step4Desc: 'Publish the new bundle CID and record the incremented policy version.',
    doneBtn: 'Return to item detail',
  },
  dev: {
    failNextOn: 'Simulate write failure: ON',
    failNextOff: 'Simulate write failure: OFF',
    toggleNotice: 'When enabled, the next on-chain transaction fails to exercise error handling.',
  },
} as const;
