/**
 * Heirloom user-facing strings. Every line states a fact the user needs.
 * Sourced from docs/DESIGN.md and specs/client-ui.md.
 */

import { Status } from './api/types';

export const COPY = {
  brand: {
    name: 'Heirloom',
    sampleNotice: 'Figures on this page are sample data.',
  },
  header: {
    defaultCollection: 'Collection HL-0007',
    defaultRole: 'Owner',
    divider: ' · ',
    create: 'Create collection',
    addItem: 'Catalogue an item',
    itemDetail: 'Item detail',
    guardians: 'Guardians and readiness',
    changes: 'Queued policy changes',
    rotate: 'Rotate secrets',
  },
  roles: {
    owner: 'Owner',
    guardian: 'Guardian',
    beneficiary: 'Beneficiary',
  },
  nav: {
    collection: 'Collection',
    notices: 'Notices',
    claims: 'Claims',
    audit: 'Audit',
    dev: 'Dev',
    register: 'Collection',
    create: 'Create',
    guardians: 'Guardians',
    changes: 'Changes',
    devStates: 'States',
    devTokens: 'Tokens',
  },
  restrictionLine: {
    [Status.Sealed]: {
      value: 'Closed',
      note: 'Last owner signature 02 Oct. Nothing pending.',
    },
    [Status.Armed]: {
      value: 'Closed',
      note: '2 of 3 attestations filed. The owner has been told.',
    },
    [Status.Silent]: {
      value: 'Closed',
      note: 'Owner silent since 19 Aug. No attestations yet.',
    },
    [Status.Cooling]: {
      label: 'Opens in',
      value: '1 d 04 h',
      note: 'The owner may cancel until then.',
    },
    [Status.Disputed]: {
      value: 'Frozen',
      note: 'One guardian reported the owner alive.',
    },
    [Status.Releasable]: {
      value: 'Open',
      note: 'Guardians may now hand over their shares.',
    },
    [Status.ContingentEligible]: {
      label: 'Primary claim period lapsed',
      value: 'Open',
      note: 'The contingent beneficiary may claim.',
    },
    [Status.Claimed]: {
      value: 'Claimed 12 Nov',
      note: 'Rotate the secrets in this item.',
    },
  },
  states: {
    empty: 'No items are catalogued in this collection yet. Add the first one to set its restriction.',
    loadingPrefix: 'Reading the chain, block ',
    defaultLoadingBlock: '14,203,118',
    error: 'The chain did not answer. Nothing was changed. Retry, or submit directly from a wallet.',
    errorFixPrompt: 'Check the network connection, or submit directly from a wallet.',
  },
  status: {
    [Status.Sealed]: 'Sealed',
    [Status.Armed]: 'Armed',
    [Status.Silent]: 'Silent',
    [Status.Cooling]: 'Cooling',
    [Status.Disputed]: 'Disputed',
    [Status.Releasable]: 'Releasable',
    [Status.ContingentEligible]: 'Contingent',
    [Status.Claimed]: 'Claimed',
  },
  table: {
    accession: 'Accession',
    item: 'Item',
    contents: 'Contents',
    quorum: 'Quorum',
    window: 'Window',
    status: 'Status',
  },
  summary: {
    owner: 'Owner',
    custodians: 'Custodians',
    items: 'Items',
    lastSigned: 'Last signed',
    epoch: 'Epoch',
    chain: 'Chain',
  },
  actions: {
    catalogueItem: 'Catalogue an item',
    submitShare: 'Submit share',
    claimAsset: 'Claim item',
    cancelProtocol: 'Cancel release',
    retry: 'Retry',
    submit: 'Submit',
    back: 'Back',
  },
  fields: {
    accessionLabel: 'Accession number',
    titleLabel: 'Item title',
    beneficiaryLabel: 'Beneficiary',
    quorumLabel: 'Attestations required',
    inactivityLabel: 'Silence window',
  },
  createCollection: {
    pageTitle: 'Create collection',
    marginLabel: 'Vault',
    paragraph: 'A collection configures custodians, beneficiaries, and thresholds. Identity cards provide signing keys and encryption public keys.',
    guardiansLabel: 'Guardian identity cards',
    guardiansHint: 'Paste one base64url JSON identity card per line.',
    beneficiariesLabel: 'Beneficiary identity cards',
    beneficiariesHint: 'Paste one base64url JSON identity card per line.',
    tLabel: 'Threshold (t)',
    nLabel: 'Guardians (n)',
    policyDelayLabel: 'Policy delay (seconds)',
    warningSlack: 'n is less than t + 2: with fewer than t + 2 guardians, a single inactive guardian reduces fault tolerance.',
    errorBeneficiaryIsGuardian: 'A beneficiary cannot also be a guardian of the same item to prevent conflicts of interest.',
    errorNeedTwo: 'At least 2 guardians and 1 beneficiary are required.',
    errorThreshold: 'Threshold t must satisfy 2 ≤ t ≤ n.',
    sampleBtn: 'Insert sample cards',
    submitBtn: 'Create collection',
    cardKindInvalid: 'Invalid kind: must be 0 (EOA) or 1 (P-256).',
    cardAInvalid: 'Invalid key a: expected 32-byte hex.',
    cardBInvalid: 'Invalid key b: expected 32-byte hex.',
    cardEncPkInvalid: 'Invalid encPk: expected 32-byte public key.',
    cardJsonInvalid: 'Invalid base64url or JSON format.',
  },
  addItem: {
    pageTitle: 'Catalogue an item',
    marginLabel: 'Item policy',
    paragraph: 'An item specifies access conditions, custodian quorums, and beneficiaries. Choose a starting policy or configure rules manually.',
    startingPointsTitle: 'Starting policies',
    sp1Title: '1 Medical records',
    sp1Desc: '14-day inactivity, 7-day window, 2 guardians, signed certificate evidence required.',
    sp2Title: '2 Letters and account list',
    sp2Desc: '30-day inactivity, 14-day window, 3 guardians, evidence not required.',
    sp3Title: '3 Seed phrase and bank credentials',
    sp3Desc: '60-day inactivity, 30-day window, 3 guardians, evidence required.',
    accessionLabel: 'Accession number',
    titleLabel: 'Item title',
    contentsLabel: 'Contents description',
    reasonsLabel: 'Release reasons',
    reasonIncapacitated: 'Incapacitated',
    reasonDeceased: 'Deceased',
    reasonMissing: 'Missing',
    inactivityLabel: 'Silence window (days)',
    kAttestLabel: 'Attestation quorum (k)',
    evidenceLabel: 'Require digital-signature evidence',
    windowLabel: 'Release window (days)',
    deadlineLabel: 'Claim deadline (days)',
    primaryBenefLabel: 'Primary beneficiary key hash',
    contingentBenefLabel: 'Contingent beneficiary key hash',
    errorKAttest: 'Attestation threshold kAttest cannot exceed n − 1 so that dispute override remains reachable.',
    errorWindow: 'Release window must be greater than zero to allow the owner to intervene.',
    submitBtn: 'Catalogue item',
  },
  itemDetail: {
    conditionsHeading: 'Release conditions',
    silenceLabel: 'Owner silence',
    silenceActive: 'Active',
    silenceSilent: 'Silent',
    quorumLabel: 'Guardian quorum',
    quorumPending: 'Pending',
    quorumReached: 'Reached',
    windowLabel: 'Release window',
    windowClosed: 'Closed',
    windowRunning: 'Running',
    windowElapsed: 'Elapsed',
    attestationsHeading: 'Guardian attestations',
    guardianCol: 'Guardian',
    attestationMarkCol: 'Mark',
    attestationDateCol: 'Filed at',
    notFiled: 'Not filed',
    filed: 'Filed',
    attestationDispute: 'Dispute (ALIVE)',
    attestationIncapacitated: 'Attested (Incapacitated)',
    attestationDeceased: 'Attested (Deceased)',
    attestationMissing: 'Attested (Missing)',
    conditionPending: 'Awaiting quorum',
    tableHeaderCondition: 'Condition',
    tableHeaderRequirement: 'Requirement',
    tableHeaderStatus: 'Status',
    tableHeaderTimestamp: 'Timestamp',
    tableHeaderKeyId: 'Key ID',
    guardianLabelPrefix: 'Guardian',
    actionsHeading: 'Interventions',
    cancelBtn: 'Cancel release',
    cancelNote: 'A signature heartbeat that resets unreleased assets and increments epoch.',
    absenceBtn: 'Set planned absence',
    absenceDaysLabel: 'Absence duration (days)',
    absenceSetSuccess: 'Absence recorded on chain.',
    summaryHeading: 'Accession record',
    summaryAssetId: 'Asset ID',
    summaryPrimaryBenef: 'Primary beneficiary',
    summaryContingentBenef: 'Contingent beneficiary',
    summaryBundleCid: 'Bundle CID',
    summaryQuorum: 'Quorum',
    summaryWindow: 'Window',
    rotatePrompt: 'This item was previously released. Cancelling does not erase released shares.',
    rotateLink: 'Rotate secrets checklist',
    notFound: 'Item not found in this collection register.',
    returnLink: 'Return to collection',
  },
  guardians: {
    pageTitle: 'Guardians and readiness',
    marginLabel: 'Custodians',
    paragraph: 'Custodians hold Shamir shares and execute periodic readiness drills without viewing asset contents or each other.',
    summaryTotal: 'Custodians (n)',
    summaryThreshold: 'Threshold (t)',
    summaryReady: 'Drill-ready',
    summarySlack: 'Slack (ready − t)',
    slackWarning: 'Slack is less than 1. Any single guardian unavailability prevents threshold reconstruction.',
    colGuardian: 'Guardian',
    colDrillVer: 'Drill version',
    colDrillDate: 'Last drill date',
    colStatus: 'Readiness',
    ready: 'Ready',
    notReady: 'Not ready',
    empty: 'No guardians are registered for this collection.',
  },
  changes: {
    pageTitle: 'Queued policy changes',
    marginLabel: 'Timelock',
    paragraph: 'Changes that make a policy looser wait in queue for the policy delay period while custodians are alerted. The owner may revoke them at any time.',
    colChange: 'Queued change',
    colApplyAfter: 'Available to apply',
    colTimeLeft: 'Time remaining',
    colAction: 'Action',
    revokeBtn: 'Revoke change',
    empty: 'No policy changes are queued in the asymmetric timelock.',
  },
  rotate: {
    pageTitle: 'Rotate secrets',
    marginLabel: 'Rotation',
    paragraph: 'This item was released before cancellation. Cryptographic shares cannot be retracted once handed over. Complete the following rotation checklist to secure replacement assets.',
    step1Title: 'Revoke exposed credentials',
    step1Desc: 'Change passwords, API keys, and device passkeys previously held in this item.',
    step2Title: 'Generate replacement credentials',
    step2Desc: 'Create new cryptographic seed phrases or locker combinations.',
    step3Title: 'Re-seal item package',
    step3Desc: 'Re-encrypt the updated contents and compute fresh Shamir shares.',
    step4Title: 'Commit updated version on chain',
    step4Desc: 'Publish the new bundle CID and record the incremented policy version.',
    doneBtn: 'Return to item detail',
  },
  tx: {
    pending: 'Waiting for the chain',
    mined: 'Recorded on the chain.',
    failedPrefix: 'Not recorded. ',
  },
  errors: {
    generic: {
      message: 'The chain did not answer. Nothing was changed.',
      fix: 'Retry, or submit directly from a wallet.',
    },
    rejectedByUser: {
      message: 'The signature request was declined. Nothing was changed.',
      fix: 'Confirm the request in the wallet to continue.',
    },
    reverts: {
      AlreadyClaimed: ['This item has already been claimed.', 'Nothing more to do here.'],
      AlreadyDisputed: ['A guardian already reported the owner alive in this epoch.', 'Wait for the owner, or for more attestations.'],
      AssetExists: ['An item with this id is already in the collection.', 'Catalogue it under a new accession number.'],
      AttestationLocked: ['Your attestation cannot be changed now.', 'You may only raise Incapacitated to Deceased, or add evidence.'],
      BadAuth: ['The signature was not accepted.', 'Sign again with the key that holds this role.'],
      BadBounds: ['A number is outside the allowed range.', 'Use at most 12 guardians, and a threshold no larger than the guardian count.'],
      BadNonce: ['The signature was out of date.', 'Retry; a fresh signature will be requested.'],
      BadPolicy: ['The item policy is not valid.', 'Check the release reasons, quorum and window, then try again.'],
      BadReason: ['That reason is not allowed for this item.', 'Choose one of the reasons the owner enabled.'],
      BadShare: ['The share is the wrong size.', 'Open your share again and retry.'],
      BeneficiaryIsGuardian: ['A beneficiary cannot also be a guardian.', 'Choose a different beneficiary or guardian.'],
      DuplicateGuardian: ['The same guardian was listed twice.', 'List each guardian once.'],
      Expired: ['The signature expired before it was recorded.', 'Retry to sign again.'],
      NoAsset: ['This item is not in the collection.', 'Return to the collection and pick an item from the list.'],
      NoShares: ['No shares have been filed for this claim yet.', 'Wait until guardians have handed over their shares.'],
      NoVault: ['This collection does not exist on this chain.', 'Check that the app is pointed at the right network.'],
      NotAuthorized: ['This key may not do that.', 'Switch to the role that holds the right key.'],
      NotClaimant: ['This key is not the current claimant.', 'Only the current claimant may receive shares.'],
      NotImplemented: ['This action is not available yet.', 'It arrives in a later release.'],
      NotReleasable: ['The item is not open yet.', 'Wait for the release window to end.'],
      ShareExists: ['Your share was already handed over.', 'Nothing more to do for this item.'],
    } as Record<string, readonly [string, string]>,
  },
  guardianNotices: {
    pageTitle: 'Notices',
    empty: 'No notices. Nothing in this collection needs a guardian.',
    colAccession: 'Accession',
    colItem: 'Item',
    colFiled: 'Attestations',
    colMine: 'Your action',
    colStatus: 'Status',
    filed: (filed: number, k: number) => `${filed} of ${k} filed`,
    mineNone: 'None',
    mineAttested: (reason: string) => `Attested, ${reason}`,
    mineDisputed: 'Reported alive',
    mineShared: 'Share handed over',
    guideLink: 'How the offline backup key works',
  },
  guardianItem: {
    countsHeading: 'Where this item stands',
    filedLabel: 'Attestations',
    sharesLabel: 'Shares handed over',
    sharesValue: (n: number, t: number) => `${n} of ${t}`,
    yourMark: 'Your attestation',
    yourDispute: 'Your dispute',
    none: 'None filed',
    disputed: 'Filed this epoch',
    actionsHeading: 'Your actions',
    attestBtn: 'Attest',
    disputeBtn: 'Dispute',
    releaseBtn: 'Release my share',
    drillBtn: 'Run drill',
    reasonLabel: 'Reason',
    reasonIncapacitated: 'Incapacitated',
    reasonDeceased: 'Deceased',
    reasonMissing: 'Missing',
    evidenceLabel: 'Evidence hash (optional)',
    evidenceInvalid: 'Expected a 32-byte hex value starting with 0x.',
    disputeExplain: 'A dispute reports that the owner is alive. It freezes every release in this collection until the owner signs again, or until enough other guardians re-affirm their attestations after your dispute.',
    drillExplain: 'The drill opens your share on this device and checks it against its commitment. Only the pass or fail result leaves your device.',
    confirmHeading: 'Confirm what you will sign',
    signAttest: (reason: string) => `You will sign an attestation that the owner is ${reason}. It applies to every item in this collection and starts the release window once the quorum is met.`,
    signDispute: 'You will sign a dispute reporting the owner alive. It freezes release until the owner signs, or until others re-affirm.',
    signRelease: 'You will open your share, encrypt it to the claimant, and sign its hand-over. It cannot be taken back.',
    signDrill: 'You will check your share locally. Nothing is signed or sent.',
    confirm: 'Confirm and sign',
    cancel: 'Back',
    drillPassed: 'Drill passed. Your share opens and matches its commitment.',
    drillFailed: 'Drill failed. Your share did not open or did not match its commitment.',
    notFound: 'This notice is not in the collection.',
    back: 'Return to notices',
    doneAttest: 'Your attestation is on the chain.',
    doneDispute: 'Your dispute is on the chain.',
    doneRelease: 'Your share was handed over.',
  },
  guide: {
    pageTitle: 'The offline backup key',
    intro: 'Your guardian key lives on one device. If that device is lost, an offline backup key lets you keep acting as a guardian.',
    steps: [
      ['Write the key down', 'Show the backup key once, write it on paper, and do not photograph it.'],
      ['Keep it away from the device', 'Store the paper somewhere the device is not: a drawer at home, or a safe.'],
      ['Tell no one where it is', 'Not the owner, not other guardians, not the beneficiary. A guardian who cannot be asked cannot be pressured.'],
      ['Restore when needed', 'On a new device choose Restore, type the key, and run a drill to confirm your share opens.'],
    ] as readonly (readonly [string, string])[],
    warning: 'Anyone who finds the paper can act as you. Anyone without it cannot restore you.',
  },
  claims: {
    pageTitle: 'Claims',
    empty: 'No items are held for you yet.',
    colAccession: 'Accession',
    colItem: 'Item',
    colStatus: 'Status',
    colProgress: 'Progress',
    progress: {
      waiting: 'Waiting',
      collecting: 'Collecting shares',
      decrypting: 'Decrypting',
      ready: 'Ready',
      claimed: 'Claimed',
    },
  },
  claim: {
    stepsHeading: 'Where your claim stands',
    waitingTitle: 'Waiting',
    waitingBody: 'The item is still closed. Guardians cannot hand over shares until the release window ends.',
    collectingTitle: 'Collecting shares',
    collectingBody: (n: number, t: number) => `${n} of ${t} received.`,
    rejectedBody: (i: number, reason: string) => `Guardian ${i}: ${reason}. This share was not counted.`,
    decryptingTitle: 'Decrypting',
    decryptingBody: 'Combining shares and decrypting on this device.',
    readyTitle: 'Ready',
    readyBody: 'The item decrypted. Download it before leaving this page; it is not stored.',
    download: 'Download',
    recording: 'Recording the claim',
    recordClaim: 'Record the claim',
    claimedTitle: 'Claimed',
    claimedBody: 'The claim is recorded.',
    rotateHeading: 'Rotate these secrets',
    rotateBody: 'Every guardian saw part of this secret. Change any password, seed phrase or combination it contained, and store the new ones separately.',
    notFound: 'This claim is not in the collection.',
    back: 'Return to claims',
  },
  audit: {
    pageTitle: 'Audit',
    empty: 'No events have been recorded for this collection.',
    colTime: 'Time',
    colEvent: 'Event',
    colActor: 'Actor',
    colTx: 'Transaction',
    filterLabel: 'Show',
    filters: {
      all: 'All',
      owner: 'Owner',
      guardian: 'Guardians',
      release: 'Release',
    },
    anonymousGuardian: 'A guardian',
    anonymousEvent: {
      Attested: 'A guardian attested.',
      Disputed: 'A guardian reported the owner alive.',
      ShareSubmitted: 'A guardian handed over a share.',
      DrillPassed: 'A guardian passed a readiness drill.',
    } as Record<string, string>,
    systemActor: 'The contract',
    viewTx: 'View',
    voided: 'Voided by a later owner action',
    event: {
      VaultCreated: (d: Record<string, string | number>) => `Collection created with ${d.guardians} guardians, threshold ${d.t}.`,
      AssetAdded: (d: Record<string, string | number>) => `Item ${d.accession ?? ''} catalogued.`.replace('  ', ' '),
      Heartbeat: (d: Record<string, string | number>) => `Owner signed. Epoch ${d.epoch}.`,
      Cancelled: (d: Record<string, string | number>) => `Owner cancelled. Pending attestations void. Epoch ${d.epoch}.`,
      AbsenceSet: () => 'Owner set a planned absence.',
      Attested: (d: Record<string, string | number>) => `Guardian ${d.guardian} attested ${String(d.reason ?? '').toLowerCase()}.`,
      Disputed: (d: Record<string, string | number>) => `Guardian ${d.guardian} reported the owner alive.`,
      DisputeOverridden: () => 'Enough attestations followed the dispute. The window restarted.',
      ShareSubmitted: (d: Record<string, string | number>) => `Guardian ${d.guardian} handed over a share${d.accession ? ` for ${d.accession}` : ''}.`,
      DrillPassed: (d: Record<string, string | number>) => `Guardian ${d.guardian} passed a readiness drill.`,
      Claimed: (d: Record<string, string | number>) => `Item ${d.accession ?? ''} claimed.`.replace('  ', ' '),
      ChangeQueued: () => 'A policy change was queued.',
      ChangeApplied: () => 'A queued policy change was applied.',
      ChangeRevoked: () => 'A queued policy change was revoked.',
      Rekeyed: () => 'An item was re-keyed.',
    } as Record<string, (d: Record<string, string | number>) => string>,
    unknownEvent: (name: string) => `${name}.`,
  },
  restriction: {
    sealed: (lastSigned: string) => `Last owner signature ${lastSigned}. Nothing pending.`,
    armed: (filed: number, k: number) => `${filed} of ${k} attestations filed. The owner has been told.`,
    silent: (since: string) => `Owner silent since ${since}. No attestations yet.`,
    claimed: 'Claimed',
  },
  dev: {
    failNextOn: 'Simulate write failure: ON',
    failNextOff: 'Simulate write failure: OFF',
    toggleNotice: 'When enabled, the next on-chain transaction fails to exercise error handling.',
  },
} as const;
